// Everything the static page displays, in one file: the page itself holds no
// data, so replacing these constants with what Grist sends is the whole of the
// wiring work.
//
// Every row is invented. It is shaped like the document — the same statuts, the
// same kinds of usage, plans with no call attached and plans with no
// commissioning year — so the page is exercised the way the real data would
// exercise it, without carrying anyone's name. The communes are real, being
// public geography and nothing more: they are what the lieu filter groups by.
import type {
    MultiSelectItem,
    MultiSelectOption,
} from '@shared/components/MultiSelect'
import type {
    ActiveFilter,
    AvisCrb,
    PlanRow,
    PlanStatut,
} from './Accueil.types'

// The values are the statuts themselves, not slugs: they are compared to what a
// row carries, so anything else would need a translation table in between — and
// « en-fonctionnement » would quietly match nothing. Only the labels are for
// reading.
export const STATUT_OPTIONS: readonly MultiSelectOption<PlanStatut>[] = [
    { value: 'projet', label: 'En projet' },
    { value: 'en fonctionnement', label: 'En fonctionnement' },
    { value: 'abandonné', label: 'Abandonné' },
    { value: 'obsolète', label: 'Obsolète' },
]

// Grouped by département: 28 communes in a flat list would be unreadable, and a
// group's checkbox toggles all of its options at once — which is exactly
// « filtrer par département ». The values stay the raw commune strings, so
// matching a row needs no parsing.
export const LIEU_OPTIONS: readonly MultiSelectItem<string>[] = [
    {
        id: 'cantal',
        label: 'Cantal (15)',
        options: [{ value: 'Vabres (15)', label: 'Vabres (15)' }],
    },
    {
        id: 'charente',
        label: 'Charente (16)',
        options: [
            { value: 'Angoulême (16)', label: 'Angoulême (16)' },
            { value: 'Châteaubernard (16)', label: 'Châteaubernard (16)' },
            {
                value: 'Exideuil-sur-Vienne (16)',
                label: 'Exideuil-sur-Vienne (16)',
            },
        ],
    },
    {
        id: 'charente-maritime',
        label: 'Charente-Maritime (17)',
        options: [
            {
                value: "Saint-Jean-d'Angély (17)",
                label: "Saint-Jean-d'Angély (17)",
            },
        ],
    },
    {
        id: 'creuse',
        label: 'Creuse (23)',
        options: [{ value: 'Guéret (23)', label: 'Guéret (23)' }],
    },
    {
        id: 'dordogne',
        label: 'Dordogne (24)',
        options: [
            { value: 'Baneuil (24)', label: 'Baneuil (24)' },
            { value: 'Creysse (24)', label: 'Creysse (24)' },
            { value: 'Moulin-Neuf (24)', label: 'Moulin-Neuf (24)' },
            { value: 'Négrondes (24)', label: 'Négrondes (24)' },
            { value: 'Salagnac (24)', label: 'Salagnac (24)' },
        ],
    },
    {
        id: 'gironde',
        label: 'Gironde (33)',
        options: [
            { value: 'Bègles (33)', label: 'Bègles (33)' },
            { value: 'Hourtin (33)', label: 'Hourtin (33)' },
            { value: 'Saint-Loubès (33)', label: 'Saint-Loubès (33)' },
            { value: 'Salles (33)', label: 'Salles (33)' },
        ],
    },
    {
        id: 'landes',
        label: 'Landes (40)',
        options: [
            { value: 'Labouheyre (40)', label: 'Labouheyre (40)' },
            { value: 'Léon (40)', label: 'Léon (40)' },
            { value: 'Solférino (40)', label: 'Solférino (40)' },
        ],
    },
    {
        id: 'lot-et-garonne',
        label: 'Lot-et-Garonne (47)',
        options: [
            {
                value: 'Fargues-sur-Ourbise (47)',
                label: 'Fargues-sur-Ourbise (47)',
            },
        ],
    },
    {
        id: 'pyrenees-atlantiques',
        label: 'Pyrénées-Atlantiques (64)',
        options: [
            { value: 'Jurançon (64)', label: 'Jurançon (64)' },
            { value: 'Lacq (64)', label: 'Lacq (64)' },
        ],
    },
    {
        id: 'deux-sevres',
        label: 'Deux-Sèvres (79)',
        options: [
            { value: 'Champdeniers (79)', label: 'Champdeniers (79)' },
            { value: 'Magné (79)', label: 'Magné (79)' },
            { value: 'Sauzé-entre-Bois (79)', label: 'Sauzé-entre-Bois (79)' },
        ],
    },
    {
        id: 'vienne',
        label: 'Vienne (86)',
        options: [
            { value: 'Naintré (86)', label: 'Naintré (86)' },
            { value: 'Poitiers (86)', label: 'Poitiers (86)' },
        ],
    },
    {
        id: 'haute-vienne',
        label: 'Haute-Vienne (87)',
        options: [
            {
                value: "Bosmie-l'Aiguille (87)",
                label: "Bosmie-l'Aiguille (87)",
            },
            {
                value: 'Saillat-sur-Vienne (87)',
                label: 'Saillat-sur-Vienne (87)',
            },
        ],
    },
]

export const APPEL_A_PROJET_OPTIONS: readonly MultiSelectOption<string>[] = [
    { value: 'BOIS ÉNERGIE (2023)', label: 'BOIS ÉNERGIE (2023)' },
    { value: 'CHALEUR INDUS (2022)', label: 'CHALEUR INDUS (2022)' },
    { value: 'CHALEUR INDUS (2023)', label: 'CHALEUR INDUS (2023)' },
    { value: 'CHALEUR+ (2024)', label: 'CHALEUR+ (2024)' },
    { value: 'CHIMIE VERTE (2023)', label: 'CHIMIE VERTE (2023)' },
    { value: 'DÉCARB INDUS (2024)', label: 'DÉCARB INDUS (2024)' },
    { value: 'FILIÈRE BOIS (2023)', label: 'FILIÈRE BOIS (2023)' },
    { value: 'FILIÈRE BOIS (2024)', label: 'FILIÈRE BOIS (2024)' },
    { value: 'GRANULÉS NA (2023)', label: 'GRANULÉS NA (2023)' },
    { value: 'HISTORIQUE (2005)', label: 'HISTORIQUE (2005)' },
    { value: '', label: 'Aucun' },
]

export const AVIS_CRB_OPTIONS: readonly MultiSelectOption<AvisCrb>[] = [
    { value: 'favorable', label: 'Favorable' },
    { value: 'favorable avec réserve', label: 'Favorable avec réserve' },
    { value: 'défavorable', label: 'Défavorable' },
    { value: 'en attente', label: 'En attente' },
]

export const ACTIVE_FILTERS: readonly ActiveFilter[] = [
    { id: 'statut', label: 'statut : en projet, en fonctionnement' },
    { id: 'region', label: 'région : Nouvelle-Aquitaine' },
]

export const PLANS: readonly PlanRow[] = [
    {
        id: 1,
        nom: 'Chaufferie de Val-Fleuri',
        departementDeSituation: 'Poitiers (86)',
        appelAProjet: 'CHALEUR+ (2024)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable',
    },
    {
        id: 2,
        nom: 'RCU Les Grands Prés',
        departementDeSituation: 'Guéret (23)',
        appelAProjet: 'GRANULÉS NA (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'en attente',
    },
    {
        id: 3,
        nom: 'Scierie du Haut-Bois',
        departementDeSituation: 'Fargues-sur-Ourbise (47)',
        appelAProjet: 'FILIÈRE BOIS (2023)',
        type: 'création',
        usage: 'matériau',
        miseEnServiceProjet: 2029,
        natureDonnee: 'prévision',
        statut: 'abandonné',
        avisCrb: 'défavorable',
    },
    {
        id: 4,
        nom: 'RCU Rive-Verte',
        departementDeSituation: 'Poitiers (86)',
        appelAProjet: 'CHALEUR+ (2024)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable avec réserve',
    },
    {
        id: 5,
        nom: 'Panneaux Bois du Causse',
        departementDeSituation: 'Salles (33)',
        appelAProjet: '',
        type: 'création',
        usage: 'matériau',
        miseEnServiceProjet: 2023,
        natureDonnee: 'constat',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 6,
        nom: 'Séchoir de la Vallée Claire',
        departementDeSituation: 'Léon (40)',
        appelAProjet: '',
        type: 'création',
        usage: 'matériau',
        miseEnServiceProjet: 2023,
        natureDonnee: 'constat',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 7,
        nom: 'Menuiseries de Fontaine-Ronde',
        departementDeSituation: "Saint-Jean-d'Angély (17)",
        appelAProjet: '',
        type: 'création',
        usage: 'matériau',
        miseEnServiceProjet: 2023,
        natureDonnee: 'prévision',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 8,
        nom: 'Verrerie de Beauregard',
        departementDeSituation: 'Châteaubernard (16)',
        appelAProjet: 'DÉCARB INDUS (2024)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable',
    },
    {
        id: 9,
        nom: 'Menuiseries de Fontaine-Ronde 2',
        departementDeSituation: "Saint-Jean-d'Angély (17)",
        appelAProjet: 'BOIS ÉNERGIE (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'en attente',
    },
    {
        id: 10,
        nom: 'Scierie de Roche-Longue C',
        departementDeSituation: 'Négrondes (24)',
        appelAProjet: 'BOIS ÉNERGIE (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable avec réserve',
    },
    {
        id: 11,
        nom: 'Gélatines de Bel-Air',
        departementDeSituation: 'Angoulême (16)',
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2027,
        natureDonnee: 'prévision',
        statut: 'abandonné',
        avisCrb: 'défavorable',
    },
    {
        id: 12,
        nom: 'Cartonnerie de Fontcombe',
        departementDeSituation: 'Creysse (24)',
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'modification',
        version: 'version 3',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable',
    },
    {
        id: 13,
        nom: 'Plâtrerie de Champlong',
        departementDeSituation: 'Saint-Loubès (33)',
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2027,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'en attente',
    },
    {
        id: 14,
        nom: 'Chaudière des Sablons',
        departementDeSituation: 'Labouheyre (40)',
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable avec réserve',
    },
    {
        id: 15,
        nom: 'Fromagerie du Val d’Ombre',
        departementDeSituation: 'Jurançon (64)',
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'abandonné',
        avisCrb: 'défavorable',
    },
    {
        id: 16,
        nom: 'Papeterie du Moulin Blanc',
        departementDeSituation: 'Exideuil-sur-Vienne (16)',
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable',
    },
    {
        id: 17,
        nom: 'Scierie des Quatre Vents',
        departementDeSituation: "Bosmie-l'Aiguille (87)",
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'abandonné',
        avisCrb: 'défavorable',
    },
    {
        id: 18,
        nom: 'Granulés de Terre-Haute G',
        departementDeSituation: 'Hourtin (33)',
        appelAProjet: 'BOIS ÉNERGIE (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2024,
        natureDonnee: 'prévision',
        statut: 'abandonné',
        avisCrb: 'défavorable',
    },
    {
        id: 19,
        nom: 'Scierie de Roche-Longue G',
        departementDeSituation: 'Négrondes (24)',
        appelAProjet: 'BOIS ÉNERGIE (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'en attente',
    },
    {
        id: 20,
        nom: 'RCU Les Grands Prés G',
        departementDeSituation: 'Guéret (23)',
        appelAProjet: 'CHALEUR INDUS (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable avec réserve',
    },
    {
        id: 21,
        nom: 'RCU Clair-Village',
        departementDeSituation: 'Salagnac (24)',
        appelAProjet: 'CHALEUR+ (2024)',
        type: 'modification',
        version: 'version 2',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable',
    },
    {
        id: 22,
        nom: 'RCU Clair-Village',
        departementDeSituation: 'Salagnac (24)',
        appelAProjet: 'CHALEUR+ (2024)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'obsolète',
        avisCrb: 'favorable avec réserve',
    },
    {
        id: 23,
        nom: 'Granulés de Terre-Haute C',
        departementDeSituation: 'Hourtin (33)',
        appelAProjet: 'BOIS ÉNERGIE (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2024,
        natureDonnee: 'prévision',
        statut: 'abandonné',
        avisCrb: 'défavorable',
    },
    {
        id: 24,
        nom: 'Chaudière des Sablons 2',
        departementDeSituation: 'Labouheyre (40)',
        appelAProjet: '',
        type: 'création',
        usage: 'matériau',
        miseEnServiceProjet: 2023,
        natureDonnee: 'constat',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 25,
        nom: 'Scierie de Mi-Bois C',
        departementDeSituation: 'Vabres (15)',
        appelAProjet: 'BOIS ÉNERGIE (2023)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2026,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'en attente',
    },
    {
        id: 26,
        nom: 'Sécherie des Landes Claires',
        departementDeSituation: 'Solférino (40)',
        appelAProjet: '',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: null,
        natureDonnee: 'prévision',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 27,
        nom: 'Contreplaqué de Bel-Orme C',
        departementDeSituation: 'Sauzé-entre-Bois (79)',
        appelAProjet: '',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: null,
        natureDonnee: 'constat',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 28,
        nom: 'Contreplaqué de Bel-Orme TJ',
        departementDeSituation: 'Magné (79)',
        appelAProjet: '',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: null,
        natureDonnee: 'constat',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 29,
        nom: 'Contreplaqué de Bel-Orme 3C',
        departementDeSituation: 'Magné (79)',
        appelAProjet: '',
        type: 'modification',
        version: 'version 2',
        usage: 'énergie',
        miseEnServiceProjet: null,
        natureDonnee: 'constat',
        statut: 'en fonctionnement',
        avisCrb: 'favorable',
    },
    {
        id: 30,
        nom: 'Papeterie d’Aube-Vive',
        departementDeSituation: 'Saillat-sur-Vienne (87)',
        appelAProjet: 'HISTORIQUE (2005)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2006,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable avec réserve',
    },
    {
        id: 31,
        nom: 'Bois Construction 2030',
        departementDeSituation: 'Naintré (86)',
        appelAProjet: 'FILIÈRE BOIS (2024)',
        type: 'création',
        usage: 'matériau',
        miseEnServiceProjet: null,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable',
    },
    {
        id: 32,
        nom: 'Bioraffinerie de Plaine-Sud',
        departementDeSituation: 'Lacq (64)',
        appelAProjet: 'CHIMIE VERTE (2023)',
        type: 'création',
        usage: 'chimie',
        miseEnServiceProjet: 2033,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'en attente',
    },
    {
        id: 33,
        nom: 'Chaudière BM Laiterie du Pré',
        departementDeSituation: 'Champdeniers (79)',
        appelAProjet: 'CHALEUR INDUS (2022)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'abandonné',
        avisCrb: 'défavorable',
    },
    {
        id: 34,
        nom: 'Chaudière BM Stratifiés Ouest',
        departementDeSituation: 'Baneuil (24)',
        appelAProjet: 'CHALEUR INDUS (2022)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2025,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable avec réserve',
    },
    {
        id: 35,
        nom: 'Chaudière BM Emballages Sud',
        departementDeSituation: 'Moulin-Neuf (24)',
        appelAProjet: 'CHALEUR INDUS (2022)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2024,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'favorable',
    },
    {
        id: 36,
        nom: 'Chaudière BM Hygiène Atlantique',
        departementDeSituation: 'Bègles (33)',
        appelAProjet: 'CHALEUR INDUS (2022)',
        type: 'création',
        usage: 'énergie',
        miseEnServiceProjet: 2024,
        natureDonnee: 'prévision',
        statut: 'projet',
        avisCrb: 'en attente',
    },
]
